# Generated by Django 4.2.7 on 2023-11-12 16:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=50)),
                ('tour', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('media', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Paleta',
        ),
    ]
