# Generated by Django 4.2.7 on 2023-11-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_post_delete_paleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artista',
            field=models.CharField(max_length=100),
        ),
    ]
