# Generated by Django 4.2.7 on 2023-11-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_userprofiledetailview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileDetailView',
        ),
    ]
